server {
    listen 80;

    location /api/auth/ {
        proxy_pass http://auth:8000/;
    }

    location /api/org/ {
        proxy_pass http://org:8000/;
    }

    location /api/core/ {
        proxy_pass http://core:8000/;
    }

    location /api/rag/ {
        proxy_pass http://rag:8000/;
    }

    location /ws/ {
        proxy_pass http://realtime:8000/;
    }

    location / {
        proxy_pass http://frontend-dev:5173;
    }
}