"""User, RefreshToken Tab updates

Revision ID: 0aed66da35d5
Revises: 6fcd5d2f890f
Create Date: 2026-07-16 12:17:42.161758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aed66da35d5'
down_revision: Union[str, Sequence[str], None] = '6fcd5d2f890f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_2fa_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###
