"""Adding location, avatar_id

Revision ID: 24f216c2ae8d
Revises: e4cbd95284ee
Create Date: 2026-07-21 10:11:35.695500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f216c2ae8d'
down_revision: Union[str, Sequence[str], None] = 'e4cbd95284ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'avatar_id',
            sa.Integer(),
            nullable=False,
            server_default='1',
        ),
    )
    op.alter_column('users', 'avatar_id', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###
