"""Adding 2fa to users tab

Revision ID: e4cbd95284ee
Revises: 0aed66da35d5
Create Date: 2026-07-21 08:28:43.497132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cbd95284ee'
down_revision: Union[str, Sequence[str], None] = '0aed66da35d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_2fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_2fa')
    # ### end Alembic commands ###
